'use strict';

const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('beast', {
  getState: () => ipcRenderer.invoke('app:state'),
  logsGet: () => ipcRenderer.invoke('logs:get'),
  logsClear: () => ipcRenderer.invoke('logs:clear'),
  listSessions: () => ipcRenderer.invoke('sessions:list'),
  createSession: () => ipcRenderer.invoke('sessions:create'),
  openSession: (id) => ipcRenderer.invoke('sessions:open', id),
  deleteSession: (id) => ipcRenderer.invoke('sessions:delete', id),
  send: (sessionId, text) => ipcRenderer.invoke('agent:send', { sessionId, text }),
  interrupt: (sessionId) => ipcRenderer.invoke('agent:interrupt', sessionId),
  setModel: (sel) => ipcRenderer.invoke('model:set', sel),
  pickWorkspace: () => ipcRenderer.invoke('cwd:set'),
  openExternal: (url) => ipcRenderer.send('open-external', url),
  getMemory: () => ipcRenderer.invoke('memory:get'),
  agentsList: () => ipcRenderer.invoke('agents:list'),
  agentsDetail: (id) => ipcRenderer.invoke('agents:detail', id),
  agentsCancel: (id) => ipcRenderer.invoke('agents:cancel', id),
  getCeoMode: () => ipcRenderer.invoke('ceo:get'),
  setCeoMode: (v) => ipcRenderer.invoke('ceo:set', v),
  listNotes: () => ipcRenderer.invoke('notes:list'),
  clearNotes: (id) => ipcRenderer.invoke('notes:clear', id),
  saveMemory: (file, content) => ipcRenderer.invoke('memory:save', { file, content }),
  listSkills: () => ipcRenderer.invoke('skills:list'),
  openSkillsFolder: () => ipcRenderer.invoke('skills:openFolder'),
  draftsList: () => ipcRenderer.invoke('skills:drafts:list'),
  draftAccept: (id) => ipcRenderer.invoke('skills:drafts:accept', id),
  draftDrop: (id) => ipcRenderer.invoke('skills:drafts:drop', id),
  rulesGet: () => ipcRenderer.invoke('rules:get'),
  ruleAdd: (t) => ipcRenderer.invoke('rules:add', t),
  ruleRemove: (id) => ipcRenderer.invoke('rules:remove', id),
  eventsGetConfig: () => ipcRenderer.invoke('events:config:get'),
  eventsSetConfig: (cfg) => ipcRenderer.invoke('events:config:set', cfg),
  eventsSubs: () => ipcRenderer.invoke('events:subs:list'),
  eventUnsub: (id) => ipcRenderer.invoke('events:subs:remove', id),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  getFallout: () => ipcRenderer.invoke('fallout:get'),
  setFallout: (cfg) => ipcRenderer.invoke('fallout:set', cfg),
  getLimits: () => ipcRenderer.invoke('limits:get'),
  setLimits: (cfg) => ipcRenderer.invoke('limits:set', cfg),
  secGet: () => ipcRenderer.invoke('sec:get'),
  secSet: (cfg) => ipcRenderer.invoke('sec:set', cfg),
  approvalRespond: (id, ok, always) => ipcRenderer.invoke('approval:respond', { id, ok, always }),
  sttTranscribe: (b64) => ipcRenderer.invoke('stt:transcribe', b64),
  updateStatus: () => ipcRenderer.invoke('update:status'),
  updateCheck: () => ipcRenderer.invoke('update:check'),
  updateInstall: () => ipcRenderer.invoke('update:install'),
  updateSetAuto: (cfg) => ipcRenderer.invoke('update:setAuto', cfg),
  setModel: (sel) => ipcRenderer.invoke('model:set', sel),
  setRoleModels: (map) => ipcRenderer.invoke('model:role', map),
  deleteModel: (sel) => ipcRenderer.invoke('model:delete', sel),
  restoreModel: (sel) => ipcRenderer.invoke('model:restore', sel),
  setVisibleModels: (list) => ipcRenderer.invoke('visible-models:set', list),
  refreshModels: () => ipcRenderer.invoke('models:refresh'),
  setTheme: (t) => ipcRenderer.invoke('theme:set', t),
  toggleBrowser: () => ipcRenderer.invoke('browser:toggle'),
  browserShownGet: () => ipcRenderer.invoke('browser:shown:get'),
  browserShownSet: (v) => ipcRenderer.invoke('browser:shown:set', v),
  terminalToggle: () => ipcRenderer.invoke('terminal:toggle'),
  terminalRun: (cmd, shell) => ipcRenderer.invoke('terminal:run', { cmd, shell }),
  terminalStop: () => ipcRenderer.invoke('terminal:stop'),
  thinkSet: (v) => ipcRenderer.invoke('think:set', v),
  exaGet: () => ipcRenderer.invoke('exa:get'),
  exaSet: (key) => ipcRenderer.invoke('exa:set', key),
  exaClear: () => ipcRenderer.invoke('exa:clear'),
  tinyfishGet: () => ipcRenderer.invoke('tinyfish:get'),
  tinyfishSet: (key) => ipcRenderer.invoke('tinyfish:set', key),
  tinyfishClear: () => ipcRenderer.invoke('tinyfish:clear'),
  browserNavigate: (url) => ipcRenderer.invoke('browser:navigate', url),
  browserCtrl: (action) => ipcRenderer.invoke('browser:ctrl', action),
  browserSetWidth: (w) => ipcRenderer.invoke('browser:setWidth', w),
  browserSetIgnoreMouse: (flag) => ipcRenderer.invoke('browser:setIgnoreMouse', flag),
  browserScreenshot: () => ipcRenderer.invoke('browser:screenshot'),
  cronList: () => ipcRenderer.invoke('cron:list'),
  cronAdd: (job) => ipcRenderer.invoke('cron:add', job),
  cronUpdate: (id, patch) => ipcRenderer.invoke('cron:update', { id, patch }),
  cronDelete: (id) => ipcRenderer.invoke('cron:delete', id),
  cronToggle: (id) => ipcRenderer.invoke('cron:toggle', id),
  cronRunNow: (id) => ipcRenderer.invoke('cron:runNow', id),

  watchersList: () => ipcRenderer.invoke('watchers:list'),

  watchersAdd: (input) => ipcRenderer.invoke('watchers:add', input),

  watchersRemove: (id) => ipcRenderer.invoke('watchers:remove', id),

  watchersToggle: (id) => ipcRenderer.invoke('watchers:toggle', id),

  providerKeys: () => ipcRenderer.invoke('providers:keys'),

  openPath: (p) => ipcRenderer.invoke('shell:openPath', p),

  showItemInFolder: (p) => ipcRenderer.invoke('shell:showItem', p),
  setCustomProviders: (list) => ipcRenderer.invoke('custom:set', list),
  fetchModels: (opts) => ipcRenderer.invoke('custom:fetchModels', opts),
  waStart: () => ipcRenderer.invoke('wa:start'),
  waStop: () => ipcRenderer.invoke('wa:stop'),
  waReset: () => ipcRenderer.invoke('wa:reset'),
  waStatus: () => ipcRenderer.invoke('wa:status'),
  waGetAllow: () => ipcRenderer.invoke('wa:allow:get'),
  waSetAllow: (list) => ipcRenderer.invoke('wa:allow:set', list),
  setWaLockdown: (v) => ipcRenderer.invoke('wa:lockdown:set', v),
  waGetTts: () => ipcRenderer.invoke('wa:tts:get'),
  waSetTts: (cfg) => ipcRenderer.invoke('wa:tts:set', cfg),
  waGetGroups: () => ipcRenderer.invoke('wa:groups:get'),
  waSetGroups: (cfg) => ipcRenderer.invoke('wa:groups:set', cfg),
  getUsage: () => ipcRenderer.invoke('usage:get'),
  resetUsage: () => ipcRenderer.invoke('usage:reset'),
  createBackup: () => ipcRenderer.invoke('backup:create'),
  restoreBackup: () => ipcRenderer.invoke('backup:restore'),
  setupStatus: () => ipcRenderer.invoke('setup:status'),
  setupSaveProvider: (p) => ipcRenderer.invoke('setup:saveProvider', p),
  setupComplete: (o) => ipcRenderer.invoke('setup:complete', o),
  setupSkip: () => ipcRenderer.invoke('setup:skip'),
  whereWasIGet: () => ipcRenderer.invoke('wherewasi:get'),
  whereWasISet: (cfg) => ipcRenderer.invoke('wherewasi:set', cfg),
  getEmail: () => ipcRenderer.invoke('email:get'),
  setEmail: (cfg) => ipcRenderer.invoke('email:set', cfg),
  captureScreen: () => ipcRenderer.invoke('screen:capture'),
  waListSessions: () => ipcRenderer.invoke('wa:sessions'),
  onWaEvent: (cb) => ipcRenderer.on('wa:event', (_e, ev) => cb(ev)),
  onEvent: (cb) => ipcRenderer.on('agent:event', (_e, ev) => cb(ev)),
});
